### ISSUE TITLE
ReferenceError: describe is not defined

### ISSUE THREAD

**Issue by mtwalsh** [vazco/meteor-universe-e2e#9]
Hi,

Thank you for releasing this package.

I'm getting an error when I run an app (Meteor v1.6.0.1) in test mode `meteor test --full-app --driver-package universe:e2e --settings settings.json --raw-logs`:
```
ReferenceError: describe is not defined
    at my-test.app-tests.js (test/my-test.app-tests.js:2:1)
    at fileEvaluate (packages\modules-runtime.js:343:9)
    at require (packages\modules-runtime.js:238:16)
    at C:\Users\micha\AppData\Local\Temp\meteor-test-rund03k4w.t2nqq\.meteor\local\build\programs\server\app\app.js:78843:1
    at infos.forEach.info (C:\Users\micha\AppData\Local\Temp\meteor-test-rund03k4w.t2nqq\.meteor\local\build\programs\server\boot.js:414:13)
    at Array.forEach (<anonymous>)
    at C:\Users\micha\AppData\Local\Temp\meteor-test-rund03k4w.t2nqq\.meteor\local\build\programs\server\boot.js:413:9
    at C:\Users\micha\AppData\Local\Temp\meteor-test-rund03k4w.t2nqq\.meteor\local\build\programs\server\boot.js:463:5
    at Function.run (C:\Users\micha\AppData\Local\Temp\meteor-test-rund03k4w.t2nqq\.meteor\local\build\programs\server\profile.js:510:12)
    at C:\Users\micha\AppData\Local\Temp\meteor-test-rund03k4w.t2nqq\.meteor\local\build\programs\server\boot.js:462:11
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

`my-test.app-tests.js`:
```javascript
var assert = require('assert');
describe('Array', function() {
    describe('#indexOf()', function() {
        it('should return -1 when the value is not present', function() {
            assert.equal([1,2,3].indexOf(4), -1);
        });
    });
});
```

In my `package.json` I have:
```javascript
"devDependencies": {
  "mocha": "^4.1.0",
  "puppeteer": "^1.0.0"
}
```

In the `settings.json` I have:
```javascript
"universe:e2e": {
    "mocha": {
        "reporter": "list"
    }
}
```
Any suggestions would be gratefully received!

**Comment by zendranm** [comment]
Hi,

We are closing this issue as it seems that it’s no longer relevant. If the problem still persists we will reopen this issue.
